import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const KEY='guide-exhibits-v2';
const MAX_HISTORY=5;
const FIELDS=[['title','展项标题'],['room','所在展厅'],['type','内容类型'],['desc','展项介绍'],['audio','语音导览 URL']];
// 每个标签页一个编辑者身份，用于版本可追溯
const editorId=(()=>{let id=sessionStorage.getItem('guide-editor-id');if(!id){id='编辑-'+Math.random().toString(36).slice(2,6).toUpperCase();sessionStorage.setItem('guide-editor-id',id)}return id})();
const T=Date.now();
const seed=[
 {id:1,color:'#e6b45d',currentVersion:2,publishedVersion:1,versions:[
  {v:1,savedAt:T-86400000*2,savedBy:'策展组',note:'初始版本',data:{title:'潮汐之后',room:'A01 · 主展厅',type:'装置',desc:'一件记录海岸线变化的沉浸式影像装置。',audio:'https://example.com/audio.mp3'}},
  {v:2,savedAt:T-3600000*5,savedBy:'策展组',note:'补充介绍文案',data:{title:'潮汐之后',room:'A01 · 主展厅',type:'装置',desc:'一件记录海岸线变化的沉浸式影像装置，现场配有定向声场。',audio:'https://example.com/audio.mp3'}}]},
 {id:2,color:'#ef8f84',currentVersion:1,publishedVersion:null,versions:[
  {v:1,savedAt:T-3600000*26,savedBy:'策展组',note:'初始版本',data:{title:'未寄出的信',room:'B02 · 纸上时间',type:'档案',desc:'来自三代人的手写信件与声音档案。',audio:''}}]},
 {id:3,color:'#83b9b1',currentVersion:1,publishedVersion:1,versions:[
  {v:1,savedAt:T-3600000*8,savedBy:'策展组',note:'初始版本',data:{title:'柔软的边界',room:'C01 · 新媒介',type:'互动',desc:'观众的移动会改变墙面上的光影。',audio:''}}]}];
const load=()=>{try{return JSON.parse(localStorage.getItem(KEY))||seed}catch{return seed}};
const persist=s=>localStorage.setItem(KEY,JSON.stringify(s));
const curData=ex=>ex.versions.find(v=>v.v===ex.currentVersion).data;
const pubData=ex=>ex.publishedVersion==null?null:ex.versions.find(v=>v.v===ex.publishedVersion).data;
const statusOf=ex=>ex.publishedVersion==null?{label:'草稿',cls:'draft'}:ex.publishedVersion===ex.currentVersion?{label:'已发布',cls:'live'}:{label:'有更新未发布',cls:'stale'};
// 追加版本并裁剪历史：最多保留 MAX_HISTORY 个，已发布版本永不裁剪
const pushVersion=(ex,ver)=>{ex.versions.push(ver);while(ex.versions.length>MAX_HISTORY){const i=ex.versions.findIndex(v=>v.v!==ex.publishedVersion);if(i<0)break;ex.versions.splice(i,1)}};
const relTime=t=>{const s=Math.max(0,Math.floor((Date.now()-t)/1000));if(s<15)return '刚刚';if(s<60)return s+' 秒前';const m=Math.floor(s/60);if(m<60)return m+' 分钟前';const h=Math.floor(m/60);if(h<24)return h+' 小时前';return Math.floor(h/24)+' 天前'};
const fmtTime=t=>new Date(t).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false});

function App(){const [exhibits,setExhibits]=useState(load);const [selected,setSelected]=useState(1);const [view,setView]=useState('edit');const [filter,setFilter]=useState('全部');const [form,setForm]=useState({title:'',room:'',type:'装置',desc:'',audio:''});const [draft,setDraft]=useState(null);const [baseVersion,setBaseVersion]=useState(1);const [conflict,setConflict]=useState(null);const [notice,setNotice]=useState('');const [,setTick]=useState(0);
 useEffect(()=>{const t=setInterval(()=>setTick(x=>x+1),30000);return()=>clearInterval(t)},[]);
 // 其他标签页保存后同步最新数据；本地草稿与 baseVersion 保持不变，用于冲突检测
 useEffect(()=>{const on=e=>{if(e.key===KEY)setExhibits(load())};window.addEventListener('storage',on);return()=>window.removeEventListener('storage',on)},[]);
 // 打开编辑页（切换展项）时记住当前版本作为编辑基线
 useEffect(()=>{const ex=load().find(x=>x.id===selected);if(!ex)return;setDraft({...curData(ex)});setBaseVersion(ex.currentVersion);setConflict(null)},[selected]);
 const current=exhibits.find(x=>x.id===selected)||exhibits[0];
 const visible=useMemo(()=>exhibits.filter(x=>filter==='全部'?true:filter==='已发布'?x.publishedVersion!=null:x.publishedVersion==null),[exhibits,filter]);
 const dirty=!!(current&&draft&&JSON.stringify(draft)!==JSON.stringify(curData(current)));
 const saveDraft=()=>{const store=load();const ex=store.find(x=>x.id===current.id);
  if(ex.currentVersion!==baseVersion){const latest=curData(ex);setExhibits(store);setConflict({latestVersion:ex.currentVersion,fields:FIELDS.filter(([k])=>latest[k]!==draft[k]).map(([k,label])=>({key:k,label,mine:draft[k],theirs:latest[k]}))});setNotice('保存被拒绝：他人已更新此展项');return}
  const ver={v:ex.currentVersion+1,savedAt:Date.now(),savedBy:editorId,note:'内容修改',data:{...draft}};pushVersion(ex,ver);ex.currentVersion=ver.v;persist(store);setExhibits([...store]);setBaseVersion(ver.v);setConflict(null);setNotice(`已保存为 v${ver.v}`)};
 const loadLatest=()=>{const store=load();const ex=store.find(x=>x.id===current.id);setExhibits(store);setDraft({...curData(ex)});setBaseVersion(ex.currentVersion);setConflict(null);setNotice(`已载入最新 v${ex.currentVersion}，请在此基础上重新修改`)};
 const publish=()=>{const store=load();const ex=store.find(x=>x.id===current.id);ex.publishedVersion=ex.currentVersion;persist(store);setExhibits([...store]);setNotice(`已发布 v${ex.currentVersion}，访客端现在显示该版本`)};
 const unpublish=()=>{const store=load();const ex=store.find(x=>x.id===current.id);ex.publishedVersion=null;persist(store);setExhibits([...store]);setNotice('已撤回发布，历史版本全部保留')};
 const restore=v=>{const store=load();const ex=store.find(x=>x.id===current.id);const src=ex.versions.find(x=>x.v===v);if(!src)return;const ver={v:ex.currentVersion+1,savedAt:Date.now(),savedBy:editorId,note:`恢复自 v${v}`,data:{...src.data}};pushVersion(ex,ver);ex.currentVersion=ver.v;persist(store);setExhibits([...store]);setDraft({...src.data});setBaseVersion(ver.v);setConflict(null);setNotice(`已把 v${v} 的内容恢复为新版本 v${ver.v}，原记录未改动`)};
 const add=()=>{if(!form.title.trim())return;const store=load();const item={id:Date.now(),color:['#e6b45d','#ef8f84','#83b9b1','#9ba7dc'][store.length%4],currentVersion:1,publishedVersion:null,versions:[{v:1,savedAt:Date.now(),savedBy:editorId,note:'创建展项',data:{...form}}]};store.push(item);persist(store);setExhibits([...store]);setSelected(item.id);setForm({title:'',room:'',type:'装置',desc:'',audio:''});setNotice('展项已保存为草稿 v1')};
 const exportData=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(load(),null,2)],{type:'application/json'}));a.download='exhibition-guide.json';a.click();setNotice('已导出展项数据（含版本历史）')};
 const pub=current&&current.publishedVersion!=null?pubData(current):null;
 if(view==='visitor') return <div className="visitor"><header><div className="brand"><span className="mark">M</span><span>潮汐美术馆</span></div><button className="ghost" onClick={()=>setView('edit')}>返回编辑</button></header><main className="visitor-main"><span className="eyebrow">VISITOR GUIDE / 2024</span><h1>沿着作品，<em>走进</em>另一种时间。</h1><p className="lead">当你靠近一件作品，它的故事就开始流动。选择一个展项开始探索。</p><div className="visitor-grid">{exhibits.filter(x=>x.publishedVersion!=null).map(x=>{const d=pubData(x);return <article className="visitor-card" key={x.id} onClick={()=>{setSelected(x.id);setView('detail')}}><div className="art" style={{background:x.color}}><span>{String(x.id).padStart(2,'0')}</span><i>↗</i></div><div className="card-meta"><small>{d.room}</small><h3>{d.title}</h3><p>{d.desc}</p></div></article>})}</div></main></div>;
 if(view==='detail'&&pub)return <div className="visitor"><header><div className="brand"><span className="mark">M</span><span>潮汐美术馆 · 导览</span></div><button className="ghost" onClick={()=>setView('visitor')}>← 全部展项</button></header><main className="detail"><div className="detail-art" style={{background:current.color}}><span>{String(current.id).padStart(2,'0')}</span></div><div className="detail-copy"><span className="eyebrow">{pub.room} / {pub.type}</span><h1>{pub.title}</h1><p>{pub.desc}</p>{pub.audio&&<button className="audio" onClick={()=>setNotice('正在播放导览音频…')}>▶ 播放语音导览</button>}<div className="qr"><div className="qr-box">▦</div><div><strong>分享这个展项</strong><small>扫描二维码，在手机上继续阅读</small></div></div></div></main>{notice&&<div className="toast">{notice}</div>}</div>;
 const st=current?statusOf(current):null;const last=current?current.versions[current.versions.length-1]:null;
 return <div className="app"><aside><div className="brand"><span className="mark">M</span><span>展览工作台</span></div><div className="side-label">当前项目</div><div className="project"><span className="project-dot"></span><div><strong>潮汐之后</strong><small>2024 春季展</small></div><span>⌄</span></div><nav><button className="active">▧ <span>展项内容</span><b>{exhibits.length}</b></button><button>⌁ <span>展厅动线</span></button><button>◉ <span>二维码</span></button></nav><div className="side-foot"><button>⚙ 设置</button><small>{editorId} · 当前 v{current?.currentVersion}</small><small>最近保存 · {last?relTime(last.savedAt):'—'}</small></div></aside><main className="workspace"><header className="topbar"><div><span className="eyebrow">EXHIBITION BUILDER</span><h1>展项内容</h1></div><div className="top-actions"><button className="secondary" onClick={exportData}>↓ 导出 JSON</button><button className="secondary" onClick={()=>setView('visitor')}>◉ 访客预览</button>{current?.publishedVersion!=null&&<button className="secondary" onClick={unpublish}>撤回发布</button>}{current&&current.publishedVersion!==current.currentVersion&&<button className="primary" onClick={publish}>发布 v{current.currentVersion} <span>↗</span></button>}</div></header><div className="content"><section className="list-pane"><div className="list-head"><div><h2>全部展项</h2><span>{exhibits.length} 个展项</span></div><button className="add-btn" onClick={()=>document.querySelector('.form-panel').scrollIntoView({behavior:'smooth'})}>＋ 添加展项</button></div><div className="filters">{['全部','已发布','草稿'].map(x=><button className={filter===x?'selected':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><div className="exhibit-list">{visible.map(x=>{const xs=statusOf(x);return <button className={'exhibit-row '+(selected===x.id?'chosen':'')} key={x.id} onClick={()=>setSelected(x.id)}><span className="thumb" style={{background:x.color}}>{String(x.id).padStart(2,'0')}</span><span className="row-copy"><strong>{curData(x).title}</strong><small>{curData(x).room} · {curData(x).type}</small></span><span className="row-ver">v{x.currentVersion}</span><span className={'status '+xs.cls}>{xs.label}</span><span className="chev">›</span></button>})}</div></section><section className="form-panel"><div className="panel-title"><div><span className="eyebrow">EDIT EXHIBIT</span><h2>编辑展项</h2></div>{st&&<span className={'status '+st.cls}>{st.label}</span>}</div>{current&&draft&&<>
 <div className="ver-bar"><span>当前版本 <b>v{current.currentVersion}</b></span><span>草稿状态 <b>{st.label}</b></span><span>最近保存 <b>{relTime(last.savedAt)}</b>（{last.savedBy}）</span>{current.publishedVersion!=null&&<span>已发布 <b>v{current.publishedVersion}</b></span>}</div>
 {conflict&&<div className="conflict"><strong>⚠ 保存被拒绝：版本冲突</strong><p>其他编辑已把此展项更新到 v{conflict.latestVersion}，你的修改基于 v{baseVersion}。{conflict.fields.length?`以下 ${conflict.fields.length} 个字段与最新版本不一致：`:'对方更新的字段与你的修改不重叠，但仍需基于最新内容重新保存。'}</p>{conflict.fields.length>0&&<ul>{conflict.fields.map(f=><li key={f.key}><span>{f.label}</span><div className="diff"><em>你的修改：{f.mine||'（空）'}</em><em>最新版本：{f.theirs||'（空）'}</em></div></li>)}</ul>}<button className="primary" onClick={loadLatest}>载入最新内容，重新修改</button></div>}
 {!conflict&&baseVersion!==current.currentVersion&&<div className="stale-banner">⚠ 他人已保存 v{current.currentVersion}，你正在基于 v{baseVersion} 编辑，直接保存会被拒绝。<button onClick={loadLatest}>载入最新内容</button></div>}
 <div className="editor"><label>展项标题<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><div className="two"><label>所在展厅<input value={draft.room} onChange={e=>setDraft({...draft,room:e.target.value})}/></label><label>内容类型<select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value})}><option>装置</option><option>档案</option><option>互动</option><option>绘画</option></select></label></div><label>展项介绍<textarea rows="5" value={draft.desc} onChange={e=>setDraft({...draft,desc:e.target.value})}/></label><label>语音导览 URL<input value={draft.audio} placeholder="https://…" onChange={e=>setDraft({...draft,audio:e.target.value})}/><small className="hint">访客扫描二维码后可播放</small></label><div className="save-row"><button className="primary" disabled={!dirty} onClick={saveDraft}>保存修改</button><small className="hint">基于 v{baseVersion}{dirty?' · 有未保存修改':' · 无改动'}</small></div><div className="preview-block"><div className="preview-heading"><span>二维码预览</span><button onClick={()=>setNotice('二维码链接已复制')}>复制链接</button></div><div className="qr-preview"><div className="qr-box big">▦</div><div><strong>展项-{String(current.id).padStart(3,'0')}</strong><small>/guide/{current.id}</small></div></div></div></div>
 <div className="history"><div className="panel-title"><div><span className="eyebrow">VERSION HISTORY</span><h2>版本历史</h2></div><span className="hint">最多保留 {MAX_HISTORY} 个 · 恢复会生成新版本</span></div>{[...current.versions].reverse().map(v=><div className={'ver-row '+(v.v===current.currentVersion?'cur':'')} key={v.v}><span className="ver-tag">v{v.v}</span><span className="ver-meta"><strong>{v.note}</strong><small>{v.savedBy} · {fmtTime(v.savedAt)}（{relTime(v.savedAt)}）</small></span>{v.v===current.publishedVersion&&<span className="status live">已发布</span>}{v.v===current.currentVersion?<span className="cur-tag">当前</span>:<button className="restore" onClick={()=>restore(v.v)}>恢复</button>}</div>)}</div>
 </>}<div className="new-form"><div className="panel-title"><div><span className="eyebrow">NEW ENTRY</span><h2>快速添加展项</h2></div></div><div className="two"><input placeholder="展项标题" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><input placeholder="展厅编号" value={form.room} onChange={e=>setForm({...form,room:e.target.value})}/></div><textarea placeholder="一句话介绍…" rows="2" value={form.desc} onChange={e=>setForm({...form,desc:e.target.value})}/><button className="primary full" onClick={add}>保存新展项</button></div></section></div></main>{notice&&<div className="toast">{notice}</div>}</div>}
createRoot(document.getElementById('root')).render(<App/>);
